package log

type flag byte

// These flags define which text to prefix to each log entry generated by the Logger.
// Bits are or'ed together to control what's printed.
const (
	FLevel flag = 1 << iota // print the log level
	FDate                   // the date in the local time zone: 2009/01/23
	FTime                   // the time in the local time zone: 01:23:23
	FMicroseconds           // requires FTime, microsecond resolution: 01:23:23.123123
	FUTC                    // use UTC instead of local time
	FFile                   // name of the file
	FPath                   // requires FFile, full path to the file
	FLine                   // requires FFile, line of the file
)
